### PR TITLE
Dx 864 rwa update docker images and node version

### PR DESCRIPTION
**Pull request by robertguss**
-updated all node versions to 16.14.0
-updated all CI config's to use [node16.14.0-slim-chrome99-ff97](https://github.com/cypress-io/cypress-docker-images/tree/master/browsers/node16.14.0-slim-chrome99-ff97)

### CODE REVIEW

**Comment by robertguss** [comment]
@admah @elylucas This PR updates all of the CI providers and the node version for the RWA to 16.14.2. There are a few flaky tests on the windows side, which I personally am not concerned about, the windows stuff is notoriously flaky with this app. Let me know if you have any questions. 

Thank you.

**Review by jordanpowell88 — APPROVED** [review]
LGTM

**Comment by robertguss** [comment]
@admah when you get a chance, can you look over this PR and see if it looks good to you?

**Comment by admah** [comment]
@robertguss do you understand the failures here? I reran the pipeline and the same failures happened.

**Comment by robertguss** [comment]
@admah the windows tests are notoriously flaky in the RWA. Kevin and I basically just ignore them as long as the other tests are passing.

**Review by admah — APPROVED** [review]
LGTM 🚀

**Pull request merged**
