### PR TITLE
Changes for Cypress 10.0.0

### PR DESCRIPTION
**Pull request by flotwig**

### CODE REVIEW

**Comment by robertguss** [comment]
@flotwig we have this PR for v10 component tests: https://github.com/cypress-io/cypress-realworld-app/pull/1104

Not sure if you are aware of it, but this was the one we had been working on.

**Comment by flotwig** [comment]
@robertguss I was not aware of that, thank you. I created this PR because I saw the `10.0.0` branch was here.

In the future it's important to name version branches with the actual version like `10.0.0`, not `kevin/component-testing`, since the App monorepo clones these example repos and runs them in CI. So commits to the monorepo have only been testing with this PR, not #1104, for the last months.

So should I close this then, and leave it to y'all to merge #1104?

**Comment by robertguss** [comment]
@flotwig yeah I think we can close this and I will merge in Kevin's PR.

**Comment by flotwig** [comment]
@robertguss Sounds good, thanks!

**Pull request closed without merging**
