### PR TITLE
chore: upgrade the windows orb

### LINKED ISSUE #1354: CircleCI uses Node.js 14.17.5 not 16.16.0 for Windows tests
## Current behavior

The workflow [.circleci/config.yml](https://github.com/cypress-io/cypress-realworld-app/blob/develop/.circleci/config.yml) which runs using the [CircleCI pipeline](https://app.circleci.com/pipelines/github/cypress-io/cypress-realworld-app) shows that it runs in Node.js `14.17.5`.

```text
 ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
 │ Cypress:        12.13.0                                                                        │
 │ Browser:        Electron 106 (headless)                                                        │
 │ Node Version:   v14.17.5 (C:\Program Files\nodejs\node.exe)                                    │
 │ Specs:          7 found (auth.spec.ts, bankaccounts.spec.ts, new-transaction.spec.ts, notifica │
 │                 tions.spec.ts, transaction-feeds.spec.ts, transaction-view.spec.ts, user-setti │
 │                 ngs.spec.ts)                                                                   │
 │ Searched:       C:\Users\circleci\project\cypress\tests\ui\*                                   │
 │ Params:         Tag: false, Group: UI - Electron - Windows, Parallel: true                     │
 │ Run URL:        https://cloud.cypress.io/projects/7s5okt/runs/6046                             │
 └────────────────────────────────────────────────────────────────────────────────────────────────┘
```

## Desired behavior

1. The Windows CI tests should use the version `16.16.0` of Node.js as defined in [.node-version](https://github.com/cypress-io/cypress-realworld-app/blob/develop/.node-version).

https://github.com/cypress-io/cypress-realworld-app/blob/761846aa99042f8b320290966d733e579944db8c/.node-version#LL1

2. Addtionally, since Node.js 14.x passed into [end-of-life status](https://github.com/nodejs/release#release-schedule) on Apr 30, 2023, it is no longer a version which should be actively used in this example repository.

## Analysis

The workflow [.circleci/config.yml](https://github.com/cypress-io/cypress-realworld-app/blob/develop/.circleci/config.yml) uses

```yml
orbs:
  cypress: cypress-io/cypress@3.1.1
  codecov: codecov/codecov@1.2.3 #
  win: circleci/windows@4.1.1
```

and

```yml
jobs:
  setup_project_and_cypress_windows:
    executor:
      # executor comes from the "windows" orb
      name: win/default
      shell: bash.exe
      size: large
```

## Suggestion

Modify the choice and setup of CircleCI to provide the Node.js `16.16.0` version for testing on Windows Server.

### PR DESCRIPTION
**Pull request by AtofStryker**
- Closes #1354

Upgrades the Circle orb from 4.x.x to 5.x.x and sets up Node 16.16.0 via nvm to be consistent with our other jobs inside circle.

### CODE REVIEW

**Comment by MikeMcC399** [comment]
@AtofStryker 

Thanks very much for making these changes!

- It looks like your tests have hit the issue I reported a while back in https://github.com/cypress-io/cypress-realworld-app/issues/1328

**Comment by AtofStryker** [comment]
> @AtofStryker
> 
> Thanks very much for making these changes!
> 
> * It looks like your tests have hit the issue I reported a while back in [Cypress Cloud times out waiting for CircleCI on Windows #1328](https://github.com/cypress-io/cypress-realworld-app/issues/1328)

Of course! I don't think fixing the timeout issues will be straight forward, but at least we can get on Node 16 here 😅

**Comment by AtofStryker** [comment]
@MikeMcC399 I have a feeling I am not going to get a passing windows run, am I? 😅

**Review by mjhenkes — APPROVED** [review]

**Comment by MikeMcC399** [comment]
@AtofStryker 

> I have a feeling I am not going to get a passing windows run, am I? 😅

I'm seeing the error message:

```
The run you are attempting to access is already complete and will not accept new groups.

The existing run is: https://cloud.cypress.io/projects/7s5okt/runs

When a run finishes all of its groups, it waits for a configurable set of time before finally completing. You must add more groups during that time period.

The --tag flag you passed was: 
The --group flag you passed was: UI - Electron - Windows
The --parallel flag you passed was: true
The --ciBuildId flag you passed was: 5e647b37
```

So to get around this, the timeout on Cypress Cloud would need to be increased. Windows takes a long time to set up.

Retriggering CircleCI would probably also not work due the timeout. To retest you would probably better push a new commit.

**Review by MikeMcC399 — APPROVED** [review]
@AtofStryker 

Congratulations 🙂 ! Apart from the flaky test (see https://github.com/cypress-io/cypress-realworld-app/issues/1332) it's all working.

So I think this PR can be merged. The other problems are all registered with their own dedicated issues, so these can be followed up separately.

**Pull request merged**
