### PR TITLE
Dockerfile added

### PR DESCRIPTION
**Pull request by Vozhak**
Provides the ability to run the app as a Docker container.

### CODE REVIEW

**Comment by Vozhak** [comment]
@mjhenkes How can I get a review?

**Comment by MikeMcC399** [comment]
@Vozhak 

Your PR proposes to run Cypress using the Docker image
`FROM node:alpine`

- Alpine Linux is however not an operating system which is supported by Cypress. See [Cypress System Requirements](https://docs.cypress.io/guides/getting-started/installing-cypress#System-requirements) and issue https://github.com/cypress-io/cypress/issues/419.

- Cypress recommends using [Cypress Docker images](https://github.com/cypress-io/cypress-docker-images). These are already used in this repository. See [.github/workflows/main.yml](https://github.com/cypress-io/cypress-realworld-app/blob/develop/.github/workflows/main.yml) which uses `cypress/browsers:node-20.12.0-chrome-123.0.6312.86-1-ff-124.0.2-edge-123.0.2420.65-1`.

If you could demonstrate and document how to use a Cypress Docker image locally this could be a useful enhancement. You should provide exact instructions and logs showing a successful run of the tests.

**Review by MikeMcC399 — CHANGES_REQUESTED** [review]
Needs to use a compatible Docker image and be documented how to use.

**Comment by MikeMcC399** [comment]
I suggest to close this PR, since there has been no feedback on the comments.

**Pull request closed without merging**
