### PR TITLE
chore(deps): update dependency @auth0/auth0-react to version 2.0.2 🌟

### PR DESCRIPTION
**Pull request by jessica-jorgenson**
I used `yarn upgrade @auth0/auth0-react@latest --dev` to update auth0

### CODE REVIEW

**Review by AtofStryker — DISMISSED** [review]
ran locally with auth0 credentials and everything seems to work as expected. We don't seem to be impacted by the 2.0.0 [changes](https://github.com/auth0/auth0-react/releases/tag/v2.0.0) so this looks G2G to me

**Comment by warrensplayer** [comment]
@jessica-jorgenson If you resolve the conflicts with `yarn.lock`, then this should be good to go.  Thanks!

**Review by AtofStryker — APPROVED** [review]

**Comment by MikeMcC399** [comment]
Either @marktnoonan needs to sign the CLA or somebody needs to rebase the PR and force push it, which would overwrite the merge branch develop into this branch.

**Review by MikeMcC399 — COMMENTED** [review]
[v2.0.2](https://github.com/auth0/auth0-react/releases/tag/v2.0.2) is no longer the latest version

Should this PR be updated to use
[v2.1.0](https://github.com/auth0/auth0-react/releases/tag/v2.1.0) 
of `@auth0/auth0-react` instead?

Also most dependencies in this repo are installed with exact versions e.g. `2.0.2` rather than semantic versions like `^2.0.2`.

**Comment by MikeMcC399** [comment]
- This PR resolves related warnings listed in https://github.com/cypress-io/cypress-realworld-app/issues/1329

```text
warning " > @auth0/auth0-react@1.9.0" has incorrect peer dependency "react@^16.11.0 || ^17".
warning " > @auth0/auth0-react@1.9.0" has incorrect peer dependency "react-dom@^16.11.0 || ^17".
```

**Comment by warrensplayer** [comment]
Updating to latest version here: https://github.com/cypress-io/cypress-realworld-app/pull/1361

**Pull request closed without merging**
